### PR TITLE
Added seekToTime, goForward, and goBack

### PR DESCRIPTION
**Pull request by brettpappas**
Created 3 new methods that let do the following:

seekToTime(sec) - moves audio position to the seconds passed
goForward(sec) - jumps ahead the number of seconds passed
goBack(sec) - jumps back the number of seconds passed

### CODE REVIEW

**Comment by tlenclos** [comment]
Seems good, could you update the Example app ? Even if not I'll try the PR tomorrow and use this function on a file.

**Comment by brettpappas** [comment]
I'd be happy to, since the Example app uses the Player component - I guess I would modify that or create a separate render function using the API instead. I will try to do this tomorrow, I also want to add a function to return audio info before playing it so I can get the duration in order to create a UI with a scrubber, play, pause, jump forward 30 and jump back 30.

**Comment by tlenclos** [comment]
Wow this willbe awesome !

**Comment by tlenclos** [comment]
Was thinking we could use https://github.com/ArnaudRinquin/react-native-radio-buttons with a vertical select in the demo. So that we could switch between multiple files / audio streams and see how the controls behave (hide jump buttons when using a stream instead of a file... etc).

**Comment by brettpappas** [comment]
I'm trying to put together a good working example of the new features using multiple audio files but I am running into a problem when I leave the previous audio playing (or paused) and then call play on a new url. It simply resumes playing the previous audio ignoring the url I pass it.

Is there an easy way to determine the current url that is loaded? I know I could track it in the react component but I don't want to rely on state or redux if I navigate somewhere else and come back. I would prefer to retrieve the information from the player since it is made to run in the background and this could be a common use case.

**Comment by tlenclos** [comment]
I think the problem is that it is resuming instead of playing the new url (maybe there https://github.com/tlenclos/react-native-audio-streaming/blob/master/ios/ReactNativeAudioStreaming.m#L74), we should compare the currently playing stream with the new one. 

Streaming kit is using a queue and itemId (https://github.com/tumtumtum/StreamingKit/blob/master/StreamingKit/StreamingKit/STKAudioPlayer.h#L249) but I don't think we should go that deep for now.

**Pull request closed without merging**
