### PR TITLE
Add Cocoapods RNAudioStreaming.podspec file

### PR DESCRIPTION
**Pull request by siriusdely**
so that we can install using these steps:
1. run `npm install react-native-audio-streaming --save`
2. add `pod 'RNAudioStreaming', :path => './node_modules/react-native-audio-streaming'` to `Podfile`
3. run `pod install`

### CODE REVIEW

**Comment by tlenclos** [comment]
Thanks ! Could you update the installation process in the README accordingly ?

**Comment by siriusdely** [comment]
README updated!

**Comment by tlenclos** [comment]
Thanks 👍

**Comment by siriusdely** [comment]
Thanks! 👍 

Just one more thing, you need to do `npm version` update/publish before everyone can do the installation steps above. Because 2.3.0 doesn't have the Podspec file yet.

**Comment by tlenclos** [comment]
Done.

**Comment by siriusdely** [comment]
OK, I have confirmed that it is working by uninstall/reinstalling npm module (2.3.1) and do pod install.

**Pull request merged**
