### PR TITLE
Update ReactNativeAudioStreaming.m

### PR DESCRIPTION
**Pull request by brettpappas**
Prevent app from stopping audio from another background app (like Music or Podcasts) whenever this app opens. This change will allow you to have this app open and still listen to audio that is already in the background. Once you play audio from this app - it will stop the any background audio from another app.

### CODE REVIEW

**Comment by tlenclos** [comment]
👍

**Comment by tlenclos** [comment]
It's better to let contributors review the pull request before merging, it could avoid breaking the develop branch too fast.

**Comment by brettpappas** [comment]
Sorry about that. I won't jump the gun again.

**Comment by tlenclos** [comment]
Anyway it was 👍  😄

**Pull request merged**
