### PR TITLE
Android exoplayer

### PR DESCRIPTION
**Pull request by cherniv**
Method getStatus response includes duration and progress

### CODE REVIEW

**Comment by tlenclos** [comment]
Hi @cherniv 
Thanks a lot for your work, I will try to make a minor release with bugfixes without exoplayer and then a major release with it.

Could you fix the indentation issues so that we can read the diff properly ?

**Comment by vshjxyz** [comment]
Hey guys, I've had a bit of a play on @cherniv's branch, adding "pause on bluetooth disconnect" "pause when removing headphones" and other fixes, will try to build a PR against this branch so you can check it out - works great tho! nice job

**Comment by cherniv** [comment]
@tlenclos i really don't know what happened with the indentations.. i've used both xcode and sublime and looks like they are messing up files formations. what can be done to fix it ? i'm not sure i want to pass on it manually if this is the only solution..
@vshjxyz cool!

**Comment by tlenclos** [comment]
@cherniv you could just revert the changes with git, using a GUI for example.

**Comment by cherniv** [comment]
@tlenclos sorry I'm not a big git master. Do you mean I have to choose bad lines from problematic commits and revert them and then create new commit and push it to my forked repo?

**Comment by tlenclos** [comment]
@cherniv Yes please. Otherwise it's just too hard to see exactly your changes.

**Comment by cherniv** [comment]
@tlenclos hey, can you see if it is better now? thanks

**Comment by catalinmiron** [comment]
any progress?

**Comment by tlenclos** [comment]
@cherniv thanks for all your work, I will merge and start from this

**Comment by tmaly1980** [comment]
@tlenclos What's required to merge this branch with master? Or in the meantime, can I simply use this branch in my project?

**Comment by guiyom19** [comment]
Will it be a 2.3.3 release with this exoplayer branch ?

**Pull request merged**
