### PR TITLE
Update aac libraries for android

### PR DESCRIPTION
**Pull request by madhu314**
This PR will be addressing [Issue #30 ](https://github.com/tlenclos/react-native-audio-streaming/issues/30)

### CODE REVIEW

**Comment by madhu314** [comment]
@tlenclos any update for this ? would you like to review this PR ?

**Comment by tlenclos** [comment]
I really want to test it against my app and will try tonight, sorry for the delay.

**Comment by madhu314** [comment]
No worries @tlenclos , just wanted to hear an update. This definitely needs a solid testing to ensure we don't break anything on android

**Comment by tlenclos** [comment]
It appears that you have the commits from this PR also https://github.com/tlenclos/react-native-audio-streaming/pull/29. I'll test all your dev and merge only this PR then.

**Comment by madhu314** [comment]
Ahh my bad, that was unintended, however if both of these are ok, please merge this and I will revoke PR #29 
otherwise, I can split these and send new PRs appropriately

**Comment by tlenclos** [comment]
Tested and approved, I'll just fix some code style and the example app on the master branch

**Pull request merged**
