### PR TITLE
Update react-native to 0.31.0

### PR DESCRIPTION
**Pull request by tlenclos**
From https://github.com/broberson/react-native-audio-streaming/commit/3169b8298e46e5f64c60017f72614ef142e2b5a1.

### CODE REVIEW

**Comment by brunocascio** [comment]
+1

**Comment by hugohow** [comment]
Is it possible to update for react-native 0.32.0 ? Thanks for the great work !

**Comment by blparker** [comment]
Or perhaps, 0.33.0, now?

**Comment by tlenclos** [comment]
Maybe someone can, this is probably an easy task but I have really no time this week sadly.

**Pull request merged**
